sudo: required
language: python
dist: xenial
python: '3.7'
services:
  - docker

before_script: cd integration

script:
  # Note: for local installs outside a virtual env, use pip3
  - pip install pipenv
  - pipenv sync
  - docker-compose pull
  - /bin/bash ./run.sh
  - cat logs/*
