version: '3'

services:

  eventbus:
    image: rabbitmq:latest

  influx:
    image: hypriot/rpi-influxdb:latest
    volumes:
    - "./influxdb/:/var/lib/influxdb/"

  history:
    image: brewblox/brewblox-history:rpi-latest
    depends_on:
      - influx
      - eventbus
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /history"
    volumes:
      - ./logs/:/app/logs/
    command:
      - "--output=/app/logs/history.txt"

  spark:
    image: brewblox/brewblox-devcon-spark:rpi-develop
    privileged: true
    depends_on:
      - eventbus
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /spark"
    volumes:
      - ./logs/:/app/logs/
      - ./brewblox/:/app/brewblox/
    command:
      - "--output=/app/logs/history.txt"
      - "--database=/app/brewblox/brewblox_db.json"
      - "--unit-system-file=/app/config/celsius_system.txt"

  traefik:
    image: traefik
    command: -c /dev/null --api --docker --docker.domain=docker.localhost
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
