version: '3'

services:
  eventbus:
    image: rabbitmq:alpine

  influx:
    image: influxdb:alpine

  history:
    build: ../images/brewblox-history
    depends_on:
      - influx
      - eventbus
    # volumes:
      # Uncomment this to use host machine packages instead of PyPi
      # - ~/.local/lib/python3.6/site-packages:/usr/local/lib/python3.6/site-packages

  simulator:
    build: ../images/brewblox-simulator
    depends_on:
      - eventbus
    # volumes:
      # Uncomment this to use host machine packages instead of PyPi
      # - ~/.local/lib/python3.6/site-packages:/usr/local/lib/python3.6/site-packages
    environment:
      # We changed the service name - HAProxy virtual host also needs an update
      - VIRTUAL_HOST=*/sim/*
    command:
      # Example: specify default service name
      - --name=sim

  gateway:
    image: dockercloud/haproxy
    links:
      - history
      - simulator
    ports:
      - "80:80"
      # stats port
      - "1936:1936"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
