version: '3'

services:
  eventbus:
    image: rabbitmq:alpine
    network_mode: host
    ports:
      - "5672:5672"

  influx:
    image: influxdb:alpine
    network_mode: host
    ports:
      - "8086:8086"

  gateway:
    image: quay.io/hellofresh/janus
    network_mode: host
    ports:
      - "8080:8080"
      - "8081:8081"

  history:
    build: ../images/brewblox-history
    network_mode: host
    ports:
      - "5000:5000"
    depends_on:
      - gateway
      - influx
      - eventbus
