version: '3'

services:
  eventbus:
    image: rabbitmq:management
    ports:
      # Allow external status checks
      - "15672:15672"

  influx:
    image: influxdb:alpine
    ports:
      # Allow external status checks
      - "8086:8086"

  history:
    image: brewblox/brewblox-history:develop
    depends_on:
      - influx
      - eventbus
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /history"

  publisher:
    image: brewblox/brewblox-service:develop
    depends_on:
      - eventbus
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /publisher"
    command:
      - "--name=publisher"

  sparksimulator:
    image: brewblox/firmware-simulator
    volumes:
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
    ports:
        - "8332"

  spark:
    image: brewblox/brewblox-devcon-spark:feature-rework-cbox-commands
    privileged: true
    depends_on:
      - eventbus
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /spark"
    command:
      - "--simulation"
      - "--broadcast-interval=1"
      - "--unit-system-file=/app/config/celsius_system.txt"
      - "--device-url=sparksimulator"
      - "--device-url-port=8332"

  # sparktest:
  #   image: brewblox/integration
  #   build: "."
  #   depends_on:
  #     - traefik
  #     - spark
  #     - history
  #     - publisher
  #     - influx
  #     - eventbus
  #   volumes:
  #     - "./test:/app/test"

  traefik:
    image: traefik
    command: -c /dev/null --api --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
