version: '3'

services:

  mdns:
    image: brewblox/brewblox-mdns:develop
    network_mode: host
    restart: unless-stopped

  eventbus:
    image: rabbitmq:alpine
    restart: unless-stopped

  influx:
    image: influxdb
    restart: unless-stopped
    volumes:
      - ./influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_LOGGING_LEVEL=warn

  datastore:
    image: treehouses/couchdb
    restart: unless-stopped
    labels:
      - "traefik.port=5984"
      - "traefik.frontend.rule=PathPrefixStrip: /datastore"
    volumes:
      - ./couchdb/:/opt/couchdb/data/

  spark:
    image: brewblox/brewblox-devcon-spark:develop
    privileged: true
    depends_on:
      - eventbus
      - datastore
    restart: unless-stopped
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /spark"

  history:
    image: brewblox/brewblox-history:develop
    depends_on:
      - influx
      - eventbus
    restart: unless-stopped
    labels:
      - "traefik.port=5000"
      - "traefik.frontend.rule=PathPrefix: /history"

  ui:
    image: brewblox/brewblox-ui:develop
    restart: unless-stopped
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=PathPrefix: /"

  traefik:
    image: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik:/config
      - /var/run/docker.sock:/var/run/docker.sock
    command: -c /config/traefik.toml --docker --docker.domain=brewblox.local
